praefixe = [
    "a-", "ab-", "aber-", "abs-", "ac-", "ad-", "af-", "ag-", "ak-", "al-", "an-",
    "anti-", "ap-", "ar-", "as-", "at-", "auf-", "aus-", "auseinander-", "be-",
    "bei-", "da-", "dafür-", "dagegen-", "daher-", "dahin-", "dahinter-",
    "daneben-", "dar", "dar-", "davon-", "davor-", "dazu-", "de-", "der-",
    "des-", "di-", "durch-", "e-", "ef-", "ein-", "ek-", "em-", "empor-",
    "en-", "ent-", "entgegen-", "entlang-", "entzwei-", "er-", "ex-", "fern-",
    "fort-", "für-", "ge-", "gegen-", "gegenüber-", "Haupt-", "heim-", "her-",
    "herab-", "heran-", "herauf-", "heraus-", "herbei-", "herein-", "hernieder-",
    "herum-", "herunter-", "hervor-", "herüber-", "hie-", "hin-", "hinab-",
    "hinan-", "hinauf-", "hinaus-", "hindurch-", "hinein-", "hinter-",
    "hinunter-", "hinweg-", "hinzu-", "hinüber-", "hoch-", "il-", "im-", "in-",
    "Ingen-", "ir-", "ko-", "kol-", "kombi-", "konter-", "kontra-", "kor-",
    "mit-", "mon-", "nach-", "neben-", "nicht-", "nieder-", "ob-", "ober-",
    "oc-", "of-", "ok-", "op-", "pop-", "Pop-", "pro-", "raus-", "re-", "red-",
    "rein-", "somato-", "suf-", "sug-", "suk-", "sup-", "super-", "sur-",
    "top-", "um-", "un-", "unter-", "ur-", "ver-", "vor-", "voran-", "vorauf-",
    "voraus-", "vorbei-", "vorüber-", "weg-", "weiter-", "wider-", "wieder-",
    "zer-", "zu-", "zurecht-", "zurück-", "zusammen-", "zwischen-", "öko-", "über-"
]

suffixe = [
    "-ab", "-abel", "-aceae", "-ade", "-affin", "-age", "-al", "-ales", "-an",
    "-ant", "-anz", "-ar", "-arisch", "-arm", "-at", "-ation", "-au", "-bar",
    "-basiert", "-bezogen", "-blütig", "-brüstig", "-chen", "-dien", "-e",
    "-eck", "-eder", "-egk", "-ei", "-el", "-elchen", "-ell", "-em", "-en",
    "-end", "-ens", "-ent", "-enz", "-er", "-erchen", "-erei", "-erich",
    "-erig", "-erisch", "-erl", "-ern", "-ert", "-esk", "-etalia", "-etea",
    "-etosum", "-ette", "-etum", "-eur", "-euse", "-fach", "-fertig", "-fizier",
    "-flach", "-frei", "-fähig", "-gebunden", "-gemäß", "-gerecht", "-gewaltige",
    "-gewaltiger", "-haft", "-halber", "-haltig", "-heit", "-hältig", "-i",
    "-ibel", "-id", "-idae", "-ie", "-iell", "-ien", "-ier", "-ifizier", "-ig",
    "-igk", "-igkeit", "-ik", "-iker", "-in", "-inae", "-ion", "-isch",
    "-isier", "-isk", "-ismus", "-ist", "-it", "-ition", "-ität", "-iv",
    "-keit", "-konform", "-kunde", "-le", "-legen", "-lei", "-lein", "-ler",
    "-lich", "-lichenes", "-ling", "-lings", "-los", "-ma", "-mal", "-mann",
    "-mar", "-maßen", "-ment", "-mycetes", "-mycetidae", "-ner", "-nis", "-nom",
    "-oat", "-ohrig", "-oid", "-oide", "-ol", "-om", "-on", "-opsida", "-or",
    "-orisch", "-ose", "-osum", "-ow", "-path", "-pflichtig", "-phyceae",
    "-phycidae", "-phyta", "-rich", "-s", "-sal", "-sam", "-sch", "-schaft",
    "-schwemme", "-seitig", "-seits", "-sel", "-selig", "-sicher", "-spurig",
    "-stan", "-tel", "-thiol", "-thion", "-tion", "-tum", "-ung", "-weise",
    "-werk", "-wertig", "-wärts", "-yl", "-zen", "-zig", "-zügig", "-är",
    "-äugig", "-ös"
]